/* Copyright 2021 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: Auto generated files. Please do not change.

package metadata_store_go_wrap

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef _gostring_ swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
typedef _gostring_ swig_type_14;
typedef _gostring_ swig_type_15;
typedef _gostring_ swig_type_16;
typedef _gostring_ swig_type_17;
typedef _gostring_ swig_type_18;
typedef _gostring_ swig_type_19;
typedef _gostring_ swig_type_20;
typedef _gostring_ swig_type_21;
typedef _gostring_ swig_type_22;
typedef _gostring_ swig_type_23;
typedef _gostring_ swig_type_24;
typedef _gostring_ swig_type_25;
typedef _gostring_ swig_type_26;
typedef _gostring_ swig_type_27;
typedef _gostring_ swig_type_28;
typedef _gostring_ swig_type_29;
typedef _gostring_ swig_type_30;
typedef _gostring_ swig_type_31;
typedef _gostring_ swig_type_32;
typedef _gostring_ swig_type_33;
typedef _gostring_ swig_type_34;
typedef _gostring_ swig_type_35;
typedef _gostring_ swig_type_36;
typedef _gostring_ swig_type_37;
typedef _gostring_ swig_type_38;
typedef _gostring_ swig_type_39;
typedef _gostring_ swig_type_40;
typedef _gostring_ swig_type_41;
typedef _gostring_ swig_type_42;
typedef _gostring_ swig_type_43;
typedef _gostring_ swig_type_44;
typedef _gostring_ swig_type_45;
typedef _gostring_ swig_type_46;
typedef _gostring_ swig_type_47;
typedef _gostring_ swig_type_48;
typedef _gostring_ swig_type_49;
typedef _gostring_ swig_type_50;
typedef _gostring_ swig_type_51;
typedef _gostring_ swig_type_52;
typedef _gostring_ swig_type_53;
typedef _gostring_ swig_type_54;
typedef _gostring_ swig_type_55;
typedef _gostring_ swig_type_56;
typedef _gostring_ swig_type_57;
typedef _gostring_ swig_type_58;
typedef _gostring_ swig_type_59;
typedef _gostring_ swig_type_60;
typedef _gostring_ swig_type_61;
typedef _gostring_ swig_type_62;
typedef _gostring_ swig_type_63;
typedef _gostring_ swig_type_64;
typedef _gostring_ swig_type_65;
typedef _gostring_ swig_type_66;
typedef _gostring_ swig_type_67;
typedef _gostring_ swig_type_68;
typedef _gostring_ swig_type_69;
typedef _gostring_ swig_type_70;
typedef _gostring_ swig_type_71;
typedef _gostring_ swig_type_72;
typedef _gostring_ swig_type_73;
typedef _gostring_ swig_type_74;
typedef _gostring_ swig_type_75;
typedef _gostring_ swig_type_76;
extern void _wrap_Swig_free_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_metadata_store_go_wrap_111d7b2874b915fe(swig_intgo arg1);
extern uintptr_t _wrap_CreateMetadataStore_metadata_store_go_wrap_111d7b2874b915fe(swig_type_1 arg1, uintptr_t arg2);
extern void _wrap_DestroyMetadataStore_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1);
extern swig_type_2 _wrap_PutArtifactType_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_3 arg2, uintptr_t arg3);
extern swig_type_4 _wrap_GetArtifactType_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_5 arg2, uintptr_t arg3);
extern swig_type_6 _wrap_GetArtifactTypes_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_7 arg2, uintptr_t arg3);
extern swig_type_8 _wrap_GetArtifactTypesByID_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_9 arg2, uintptr_t arg3);
extern swig_type_10 _wrap_PutExecutionType_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_11 arg2, uintptr_t arg3);
extern swig_type_12 _wrap_GetExecutionType_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_13 arg2, uintptr_t arg3);
extern swig_type_14 _wrap_GetExecutionTypes_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_15 arg2, uintptr_t arg3);
extern swig_type_16 _wrap_GetExecutionTypesByID_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_17 arg2, uintptr_t arg3);
extern swig_type_18 _wrap_PutContextType_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_19 arg2, uintptr_t arg3);
extern swig_type_20 _wrap_GetContextType_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_21 arg2, uintptr_t arg3);
extern swig_type_22 _wrap_GetContextTypes_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_23 arg2, uintptr_t arg3);
extern swig_type_24 _wrap_GetContextTypesByID_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_25 arg2, uintptr_t arg3);
extern swig_type_26 _wrap_PutArtifacts_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_27 arg2, uintptr_t arg3);
extern swig_type_28 _wrap_PutExecutions_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_29 arg2, uintptr_t arg3);
extern swig_type_30 _wrap_GetArtifactsByID_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_31 arg2, uintptr_t arg3);
extern swig_type_32 _wrap_GetExecutionsByID_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_33 arg2, uintptr_t arg3);
extern swig_type_34 _wrap_PutEvents_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_35 arg2, uintptr_t arg3);
extern swig_type_36 _wrap_PutExecution_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_37 arg2, uintptr_t arg3);
extern swig_type_38 _wrap_GetEventsByArtifactIDs_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_39 arg2, uintptr_t arg3);
extern swig_type_40 _wrap_GetEventsByExecutionIDs_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_41 arg2, uintptr_t arg3);
extern swig_type_42 _wrap_GetArtifacts_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_43 arg2, uintptr_t arg3);
extern swig_type_44 _wrap_GetArtifactsByType_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_45 arg2, uintptr_t arg3);
extern swig_type_46 _wrap_GetArtifactByTypeAndName_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_47 arg2, uintptr_t arg3);
extern swig_type_48 _wrap_GetArtifactsByURI_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_49 arg2, uintptr_t arg3);
extern swig_type_50 _wrap_GetExecutions_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_51 arg2, uintptr_t arg3);
extern swig_type_52 _wrap_GetExecutionsByType_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_53 arg2, uintptr_t arg3);
extern swig_type_54 _wrap_GetExecutionByTypeAndName_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_55 arg2, uintptr_t arg3);
extern swig_type_56 _wrap_PutContexts_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_57 arg2, uintptr_t arg3);
extern swig_type_58 _wrap_GetContextsByID_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_59 arg2, uintptr_t arg3);
extern swig_type_60 _wrap_GetContexts_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_61 arg2, uintptr_t arg3);
extern swig_type_62 _wrap_GetContextsByType_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_63 arg2, uintptr_t arg3);
extern swig_type_64 _wrap_GetContextByTypeAndName_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_65 arg2, uintptr_t arg3);
extern swig_type_66 _wrap_PutAttributionsAndAssociations_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_67 arg2, uintptr_t arg3);
extern swig_type_68 _wrap_GetContextsByArtifact_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_69 arg2, uintptr_t arg3);
extern swig_type_70 _wrap_GetContextsByExecution_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_71 arg2, uintptr_t arg3);
extern swig_type_72 _wrap_GetArtifactsByContext_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_73 arg2, uintptr_t arg3);
extern swig_type_74 _wrap_GetExecutionsByContext_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1, swig_type_75 arg2, uintptr_t arg3);
extern uintptr_t _wrap_CreateABSLStatus_metadata_store_go_wrap_111d7b2874b915fe(void);
extern void _wrap_DestroyABSLStatus_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1);
extern _Bool _wrap_IsOk_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1);
extern swig_type_76 _wrap_ErrorMessage_metadata_store_go_wrap_111d7b2874b915fe(uintptr_t arg1);
#undef intgo
*/
import "C"

import (
	_ "runtime/cgo"
	"sync"
	"unsafe"
)

type _ unsafe.Pointer

var Swig_escape_always_false bool
var Swig_escape_val interface{}

type _swig_fnptr *byte
type _swig_memberptr *byte

type _ sync.Mutex

type swig_gostring struct {
	p uintptr
	n int
}

func swigCopyString(s string) string {
	p := *(*swig_gostring)(unsafe.Pointer(&s))
	r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
	Swig_free(p.p)
	return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_metadata_store_go_wrap_111d7b2874b915fe(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func CreateMetadataStore(arg1 string, arg2 Absl_Status) (_swig_ret Ml_metadata_MetadataStore) {
	var swig_r Ml_metadata_MetadataStore
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Ml_metadata_MetadataStore)(SwigcptrMl_metadata_MetadataStore(C._wrap_CreateMetadataStore_metadata_store_go_wrap_111d7b2874b915fe(*(*C.swig_type_1)(unsafe.Pointer(&_swig_i_0)), C.uintptr_t(_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func DestroyMetadataStore(arg1 Ml_metadata_MetadataStore) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_DestroyMetadataStore_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0))
}

func PutArtifactType(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_PutArtifactType_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_3)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetArtifactType(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetArtifactType_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_5)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetArtifactTypes(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetArtifactTypes_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_7)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetArtifactTypesByID(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetArtifactTypesByID_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_9)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func PutExecutionType(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_PutExecutionType_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_11)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetExecutionType(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetExecutionType_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_13)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetExecutionTypes(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetExecutionTypes_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_15)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetExecutionTypesByID(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetExecutionTypesByID_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_17)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func PutContextType(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_PutContextType_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_19)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetContextType(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetContextType_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_21)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetContextTypes(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetContextTypes_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_23)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetContextTypesByID(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetContextTypesByID_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_25)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func PutArtifacts(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_PutArtifacts_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_27)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func PutExecutions(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_PutExecutions_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_29)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetArtifactsByID(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetArtifactsByID_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_31)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetExecutionsByID(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetExecutionsByID_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_33)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func PutEvents(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_PutEvents_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_35)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func PutExecution(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_PutExecution_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_37)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetEventsByArtifactIDs(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetEventsByArtifactIDs_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_39)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetEventsByExecutionIDs(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetEventsByExecutionIDs_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_41)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetArtifacts(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetArtifacts_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_43)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetArtifactsByType(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetArtifactsByType_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_45)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetArtifactByTypeAndName(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetArtifactByTypeAndName_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_47)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetArtifactsByURI(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetArtifactsByURI_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_49)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetExecutions(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetExecutions_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_51)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetExecutionsByType(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetExecutionsByType_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_53)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetExecutionByTypeAndName(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetExecutionByTypeAndName_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_55)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func PutContexts(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_PutContexts_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_57)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetContextsByID(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetContextsByID_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_59)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetContexts(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetContexts_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_61)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetContextsByType(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetContextsByType_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_63)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetContextByTypeAndName(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetContextByTypeAndName_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_65)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func PutAttributionsAndAssociations(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_PutAttributionsAndAssociations_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_67)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetContextsByArtifact(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetContextsByArtifact_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_69)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetContextsByExecution(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetContextsByExecution_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_71)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetArtifactsByContext(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetArtifactsByContext_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_73)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetExecutionsByContext(arg1 Ml_metadata_MetadataStore, arg2 string, arg3 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r_p := C._wrap_GetExecutionsByContext_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0), *(*C.swig_type_75)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func CreateABSLStatus() (_swig_ret Absl_Status) {
	var swig_r Absl_Status
	swig_r = (Absl_Status)(SwigcptrAbsl_Status(C._wrap_CreateABSLStatus_metadata_store_go_wrap_111d7b2874b915fe()))
	return swig_r
}

func DestroyABSLStatus(arg1 Absl_Status) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_DestroyABSLStatus_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0))
}

func IsOk(arg1 Absl_Status) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_IsOk_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func ErrorMessage(arg1 Absl_Status) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_ErrorMessage_metadata_store_go_wrap_111d7b2874b915fe(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

type SwigcptrAbsl_Status uintptr
type Absl_Status interface {
	Swigcptr() uintptr
}

func (p SwigcptrAbsl_Status) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrMl_metadata_MetadataStore uintptr
type Ml_metadata_MetadataStore interface {
	Swigcptr() uintptr
}

func (p SwigcptrMl_metadata_MetadataStore) Swigcptr() uintptr {
	return uintptr(p)
}
