# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'

# Extensions are not support until 3.4 thus the repeated boilerplate below.

# We mount the MLMD project root at /build (which is the WORKDIR of the image)
# in the container.
services:
  manylinux-python37:
    image: mlmd-build:manylinux2010
    build:
      context: .
      dockerfile: ml_metadata/tools/docker_build/Dockerfile.manylinux2010
    environment:
      PYTHON_VERSION: 37
    volumes:
      - .:/build:delegated
  manylinux-python38:
    image: mlmd-build:manylinux2010
    build:
      context: .
      dockerfile: ml_metadata/tools/docker_build/Dockerfile.manylinux2010
    environment:
      PYTHON_VERSION: 38
    volumes:
      - .:/build:delegated
  manylinux-python39:
    image: mlmd-build:manylinux2010
    build:
      context: .
      dockerfile: ml_metadata/tools/docker_build/Dockerfile.manylinux2010
    environment:
      PYTHON_VERSION: 39
    volumes:
      - .:/build:delegated
  manylinux-python310:
    image: mlmd-build:manylinux2010
    build:
      context: .
      dockerfile: ml_metadata/tools/docker_build/Dockerfile.manylinux2010
    environment:
      PYTHON_VERSION: 310
    volumes:
      - .:/build:delegated
