# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Dockerfile for building a manylinux2010 MLMD wheel.
# We use manylinux2014 as it has a modern GCC.
FROM quay.io/pypa/manylinux2014_x86_64

# Install Bazel 6.5.0
RUN curl -sSL -o /usr/local/bin/bazel https://github.com/bazelbuild/bazel/releases/download/6.5.0/bazel-6.5.0-linux-x86_64 && \
    chmod +x /usr/local/bin/bazel

# Install a recent version of cmake
RUN yum install -y cmake3 && \
    ln -s /usr/bin/cmake3 /usr/bin/cmake

# Set up the environment
ENV BAZEL_VERSION=6.5.0
ENV BAZEL_OPTS="--host_jvm_args=-Xms2g --host_jvm_args=-Xmx2g"
# devtoolset-10 is pre-installed on the image, we just need to enable it.
ENV PATH="/opt/rh/devtoolset-10/root/usr/bin:${PATH}"
ENV LD_LIBRARY_PATH="/opt/rh/devtoolset-10/root/usr/lib64:/opt/rh/devtoolset-10/root/usr/lib:${LD_LIBRARY_PATH}"


WORKDIR /build
CMD ["ml_metadata/tools/docker_build/build_manylinux.sh"]