name: deploy-docs
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:

permissions:
  contents: read

jobs:
  build-check:
    name: Build docs check
    if: (github.event_name == 'pull_request')
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Python 3.12
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            setup.py
            requirements-docs.txt

      - name: Save time for cache for mkdocs
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Caching
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install Dependencies
        run: pip install -r requirements-docs.txt

      - name: Build docs to check for errors
        run: mkdocs build

  deploy:
    name: Deploy to GitHub Pages
    if: (github.event_name != 'pull_request')
    runs-on: ubuntu-latest
    # zizmor: ignore[excessive-permissions]
    permissions:
      # Required to deploy documentation to GitHub Pages (gh-pages branch)
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Python 3.12
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            setup.py
            requirements-docs.txt

      - name: Save time for cache for mkdocs
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Caching
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install Dependencies
        run: pip install -r requirements-docs.txt

      - name: Deploy to GitHub Pages
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          mkdocs gh-deploy --force
